let cards;

function goBack() {
    window.location.href = "juego_ind.html";
}

function makeCardList() {
    cards = [
        {
            ID: "c01",
            ref: document.getElementById("c01"),
            state: true
        }, {
            ID: "c02",
            ref: document.getElementById("c02"),
            state: true
        }, {
            ID: "c03",
            ref: document.getElementById("c03"),
            state: true
        }, {
            ID: "c04",
            ref: document.getElementById("c04"),
            state: true
        }, {
            ID: "c05",
            ref: document.getElementById("c05"),
            state: true
        }, {
            ID: "c06",
            ref: document.getElementById("c06"),
            state: true
        }, {
            ID: "c07",
            ref: document.getElementById("c07"),
            state: true
        }, {
            ID: "c08",
            ref: document.getElementById("c08"),
            state: true
        }, {
            ID: "c09",
            ref: document.getElementById("c09"),
            state: true
        }, {
            ID: "c10",
            ref: document.getElementById("c10"),
            state: true
        }, {
            ID: "c11",
            ref: document.getElementById("c11"),
            state: true
        }, {
            ID: "c12",
            ref: document.getElementById("c12"),
            state: true
        }, {
            ID: "c13",
            ref: document.getElementById("c13"),
            state: true
        }, {
            ID: "c14",
            ref: document.getElementById("c14"),
            state: true
        }, {
            ID: "c15",
            ref: document.getElementById("c15"),
            state: true
        }, {
            ID: "c16",
            ref: document.getElementById("c16"),
            state: true
        }, {
            ID: "c17",
            ref: document.getElementById("c17"),
            state: true
        }, {
            ID: "c18",
            ref: document.getElementById("c18"),
            state: true
        }, {
            ID: "c19",
            ref: document.getElementById("c19"),
            state: true
        }, {
            ID: "c20",
            ref: document.getElementById("c20"),
            state: true
        }, {
            ID: "c21",
            ref: document.getElementById("c21"),
            state: true
        }, {
            ID: "c22",
            ref: document.getElementById("c22"),
            state: true
        }, {
            ID: "c23",
            ref: document.getElementById("c23"),
            state: true
        }, {
            ID: "c24",
            ref: document.getElementById("c24"),
            state: true
        }, {
            ID: "c25",
            ref: document.getElementById("c25"),
            state: true
        }, {
            ID: "c26",
            ref: document.getElementById("c26"),
            state: true
        }, {
            ID: "c27",
            ref: document.getElementById("c27"),
            state: true
        }, {
            ID: "c28",
            ref: document.getElementById("c28"),
            state: true
        }, {
            ID: "c29",
            ref: document.getElementById("c29"),
            state: true
        }, {
            ID: "c30",
            ref: document.getElementById("c30"),
            state: true
        }, {
            ID: "c31",
            ref: document.getElementById("c31"),
            state: true
        }, {
            ID: "c32",
            ref: document.getElementById("c32"),
            state: true
        }, {
            ID: "c33",
            ref: document.getElementById("c33"),
            state: true
        }, {
            ID: "c34",
            ref: document.getElementById("c34"),
            state: true
        }, {
            ID: "c35",
            ref: document.getElementById("c35"),
            state: true
        }, {
            ID: "c36",
            ref: document.getElementById("c36"),
            state: true
        }, {
            ID: "c37",
            ref: document.getElementById("c37"),
            state: true
        }, {
            ID: "c38",
            ref: document.getElementById("c38"),
            state: true
        }, {
            ID: "c39",
            ref: document.getElementById("c39"),
            state: true
        }, {
            ID: "c40",
            ref: document.getElementById("c40"),
            state: true
        }, {
            ID: "c41",
            ref: document.getElementById("c41"),
            state: true
        }, {
            ID: "c42",
            ref: document.getElementById("c42"),
            state: true
        }, {
            ID: "c43",
            ref: document.getElementById("c43"),
            state: true
        }, {
            ID: "c44",
            ref: document.getElementById("c44"),
            state: true
        }, {
            ID: "c45",
            ref: document.getElementById("c45"),
            state: true
        }, {
            ID: "c46",
            ref: document.getElementById("c46"),
            state: true
        }, {
            ID: "c47",
            ref: document.getElementById("c47"),
            state: true
        }, {
            ID: "c48",
            ref: document.getElementById("c48"),
            state: true
        }, {
            ID: "c49",
            ref: document.getElementById("c49"),
            state: true
        }, {
            ID: "c50",
            ref: document.getElementById("c50"),
            state: true
        }, {
            ID: "c51",
            ref: document.getElementById("c51"),
            state: true
        }, {
            ID: "c52",
            ref: document.getElementById("c52"),
            state: true
        }, {
            ID: "c53",
            ref: document.getElementById("c53"),
            state: true
        }, {
            ID: "c54",
            ref: document.getElementById("c54"),
            state: true
        }, {
            ID: "c55",
            ref: document.getElementById("c55"),
            state: true
        }, {
            ID: "c56",
            ref: document.getElementById("c56"),
            state: true
        }, {
            ID: "c57",
            ref: document.getElementById("c57"),
            state: true
        }, {
            ID: "c58",
            ref: document.getElementById("c58"),
            state: true
        }, {
            ID: "c59",
            ref: document.getElementById("c59"),
            state: true
        }, {
            ID: "c60",
            ref: document.getElementById("c60"),
            state: true
        }, {
            ID: "c61",
            ref: document.getElementById("c61"),
            state: true
        }, {
            ID: "c62",
            ref: document.getElementById("c62"),
            state: true
        }, {
            ID: "c63",
            ref: document.getElementById("c63"),
            state: true
        }, {
            ID: "c64",
            ref: document.getElementById("c64"),
            state: true
        }];

    needed = 64;
}

function claimPrize() {
    alert(`FELICIDADES: Ganaste ${active_user.prize_group.description}`);
}